# generated by configure / remove this line to disable regeneration
prefix="/mnt/c/users/kosho/desktop/aha/clockwork"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/mnt/c/users/kosho/desktop/aha/clockwork/barvinok-0.41/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/mnt/c/users/kosho/desktop/aha/clockwork/barvinok-0.41/."
package="barvinok"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "barvinok"
;; --help) pkg-config --help ; echo Buildscript Of "barvinok Library"
;; --modversion|--version) echo "0.41"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lbarvinok -lpolylibgmp -lisl -lntl -lgmp"
       :
;; --cflags) echo -I${includedir} "-I/mnt/c/users/kosho/desktop/aha/clockwork/include"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
