# generated by configure / remove this line to disable regeneration
prefix="/mnt/c/users/kosho/desktop/aha/clockwork"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/mnt/c/users/kosho/desktop/aha/clockwork/barvinok-0.41/polylib/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/mnt/c/users/kosho/desktop/aha/clockwork/barvinok-0.41/polylib/./include"
package="polylibgmp"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "polylibgmp"
;; --help) pkg-config --help ; echo Buildscript Of "polylibgmp Library"
;; --modversion|--version) echo "5.22.5"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lpolylibgmp -lgmp"
       :
;; --cflags) echo -I${includedir} ""
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
