#catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

#set vpp_optimize_level 0
open_project mpsize_1_naive_accel
set_top mpsize_1_naive
add_files "mpsize_1_naive.cpp" -cflags " -D __VIVADO_SYNTH__ -I /home/centos/clockwork -I /home/centos/clockwork/soda_codes/mpsize_1_opt/isl_dir "
add_files -tb "regression_tb_mpsize_1_naive.cpp" -cflags " -D __VIVADO_SYNTH__ -I /home/centos/clockwork -I /home/centos/clockwork/soda_codes/mpsize_1_opt/isl_dir "
open_solution solution
set_part xcvu9p-flgb2104-2-i
create_clock -period 250.000000MHz -name default
#config_sdx -target xocc
#config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_rtl -enable_maxiConservative=1
#config_interface -m_axi_addr64
#config_export -format ip_catalog -ipname mpsize_1_naive_accel
csynth_design
cosim_design
export_design -rtl verilog -format ip_catalog -xo mpsize_1_custom_hls.xo
close_project
puts "HLS completed successfully"
exit
